# Generated by Django 2.0 on 2018-01-02 05:05

import Foro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0003_auto_20180101_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Foro.models.upload_location),
        ),
    ]
