# Generated by Django 2.0 on 2018-01-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0004_auto_20180102_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='respuestas',
            field=models.BigIntegerField(default=0),
        ),
    ]
