# Generated by Django 2.0 on 2018-01-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0005_thread_respuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
