# Generated by Django 2.0 on 2018-01-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0006_post_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
