# Generated by Django 2.0 on 2018-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0007_auto_20180107_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aprobado',
            field=models.NullBooleanField(default=None),
        ),
    ]
