# Generated by Django 2.0 on 2018-01-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0008_auto_20180108_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('titulo', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
