# Generated by Django 2.0 on 2018-01-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0009_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
        ),
    ]
