# Generated by Django 2.0 on 2018-01-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0010_auto_20180129_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='club',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=15),
        ),
    ]
