# Generated by Django 2.0 on 2018-02-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0011_auto_20180130_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('desc', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
