# Generated by Django 2.0 on 2018-02-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0012_fechas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechas',
            old_name='año',
            new_name='anio',
        ),
    ]
