# Generated by Django 2.0 on 2018-02-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0013_auto_20180212_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fechas',
            new_name='Fecha',
        ),
    ]
