# Generated by Django 2.0 on 2018-02-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0014_auto_20180212_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fecha',
            old_name='anio',
            new_name='año',
        ),
    ]
