# Generated by Django 2.0 on 2018-02-13 04:31

import Foro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0015_auto_20180212_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Foro.models.upload_fechas),
        ),
    ]
