# Generated by Django 2.0.1 on 2018-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0016_fecha_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('temperatura', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('humedad', models.DecimalField(decimal_places=10, default=0.0, max_digits=15)),
                ('ventilador', models.BooleanField()),
            ],
        ),
    ]
